# Generated by Django 3.2.20 on 2023-07-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_no', models.IntegerField()),
                ('password', models.CharField(max_length=60)),
                ('first_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ormmany.person1')),
            ],
        ),
        migrations.CreateModel(
            name='person2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='ormmany.person1')),
            ],
        ),
    ]
