# Generated by Django 4.1.10 on 2023-08-03 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 14, 43, 35, 789030)),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 3, 14, 43, 35, 790026)),
        ),
    ]
