# Generated by Django 3.2.20 on 2023-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteam_name', models.CharField(max_length=200)),
                ('iteam_code', models.IntegerField()),
                ('bar_code', models.BinaryField()),
            ],
            options={
                'db_table': 'barcode_reader',
            },
        ),
    ]
