# Generated by Django 3.2.20 on 2023-07-21 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 21, 15, 45, 18, 507865))),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
