# Generated by Django 3.2.20 on 2023-07-21 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image64',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 21, 16, 52, 30, 377304)),
        ),
    ]
