# Generated by Django 3.2.20 on 2023-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decimalvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.FloatField()),
                ('decimal_field', models.IntegerField()),
                ('converted', models.CharField(max_length=100)),
            ],
        ),
    ]
